// let data = 0

// while (data <=10){
//     console.log(`here is the first value ${data}`)
//     data = data + 2

// }

// let dataaa = true

// while ( dataaa == true ){
//     if (data == 10) {
//         dataaa = false
//     }
//         console.log(`the data says that data is ${data}`);
//         data=data + 2
// }

// let arraydata = ["rajesh","darshana","pranav"]
// let i = 0
// while (i <= arraydata.length){
//     console.log(arraydata[i])
//     i++
// }


